# Generated by Django 2.2.8 on 2020-02-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('el_travel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pole',
            name='author',
        ),
        migrations.AlterField(
            model_name='pole',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
